### ISSUE TITLE
bigsip 1.18.2 crash related to servers 

### ISSUE THREAD

**Issue by Chrino2042** [PssbleTrngle/BigSip#16]
### What happened?

running the mod in client is fine, but running it as a server results in a crash

### Mod Version

0.0.2-alpha

### Minecraft Version

1.18

### Minecraft Loader

Forge

### Fabric/Forge Version

40.1.68

### Relevant log output

```shell
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.73-universal.jar%23265!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.73-universal.jar%23265!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:1.0] {}
-- MOD bigsip --
Details:
	Caused by 0: java.lang.RuntimeException: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
		at thedarkcolour.kotlinforforge.AutoKotlinEventBusSubscriber.inject(AutoKotlinEventBusSubscriber.kt:99) ~[kotlinforforge-3.7.1-obf.jar%23170!/:3.7.1] {}
		at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:83) ~[kotlinforforge-3.7.1-obf.jar%23170!/:3.7.1] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.73.jar%23261!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: --bigsip-0.0.2-alpha.jar
	Failure message: Big Sip (bigsip) has failed to load correctly
		java.lang.RuntimeException: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
	Mod Version: 0.0.2-alpha
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.getDeclMethod(EventBus.java:83) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$4(EventBus.java:95) ~[eventbus-5.0.3.jar%232!/:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap$KeySpliterator.tryAdvance(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:97) ~[eventbus-5.0.3.jar%232!/:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-5.0.3.jar%232!/:?] {}
	at thedarkcolour.kotlinforforge.AutoKotlinEventBusSubscriber.registerTo(AutoKotlinEventBusSubscriber.kt:110) ~[kotlinforforge-3.7.1-obf.jar%23170!/:3.7.1] {}
	at thedarkcolour.kotlinforforge.AutoKotlinEventBusSubscriber.inject(AutoKotlinEventBusSubscriber.kt:96) ~[kotlinforforge-3.7.1-obf.jar%23170!/:3.7.1] {}
	at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:83) ~[kotlinforforge-3.7.1-obf.jar%23170!/:3.7.1] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.73.jar%23261!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

**Comment by PssbleTrngle** [comment]
I have not forgotten this, this mod just doesn't have a priority right now and thus is still in alpha, but I will fix this in the next release

**Comment by Chrino2042** [comment]
poggers, thank you
